### ISSUE TITLE
关于项目中Navigator组件使用的问题

### ISSUE THREAD

**Issue by cl1069573062** [Bob1993/React-Native-Gank#18]
在Facebook的官方文档中，可以看到Navigator的常规使用的方法，在学习你的开源项目中，回过头看你Navigator组件用法中，有一些不明白的地方
` <Navigator
          ref={component => this.navigator = component}

```
      initialRoute={{
        component: HomePage
      }}
      renderScene={(route, navigator) => { // 用来渲染navigator栈顶的route里的component页面
        // route={component: xxx, name: xxx, ...}， navigator.......route 用来在对应界面获取其他键值
      return <route.component navigator={navigator} {...route} {...route.passProps}/>// {...route.passProps}即就是把passProps里的键值对全部以给属性赋值的方式展开 如：test={10}
    }}/>
```

```
在你的用法中，我不明白ref={component => this.navigator = component}这段代码的意思？希望能了解下，这段代码的设计的作用和用法的意思，谢谢

```

**Comment by poberwong** [comment]
## 很抱歉，这么晚才回复你

这是ref的两种用法之一，众所周知，React中，使用ref来获取虚拟节点instead of jQuery：
- Method1: 

```
<Navigator
  ref={component => this.navigator = component}
/>
```

_任意组件都提供ref属性，以此给外界提供当前组件的虚拟Dom 节点_ 
这是组件ref属性的一种写法，这样就直接将Navigator直接绑定在了当前class实例this上，你也可以看到在back键处理的函数里（应用的顶层容器）用到了Navigator分情况来处理back键的响应。
- Method2:

```
ref='navigator'
```

不过这样ref是存在了this的refs数组里，使用时需要`this.refs.navigator`
so much for this.

> 如果你对Back键的写法有疑问，可以看我这篇文章: [Back键的攻坚实战](http://www.jianshu.com/p/44e415a3cb0b)
> 如果你对Navigator有疑问，可以看我这篇文章: [解密Navigator组件](http://www.jianshu.com/p/03ddca8f1982), Navigator 用法比较灵活，改天我会抽时间完善这篇博客
